name: Build DLL

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Build DLL
        run: |
          g++ -shared -o mycheats.dll mycheats.cpp -ld3d9 -ld3dx9

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: mycheats-dll
          path: mycheats.dll