name: Build DLL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile DLL
      run: cl /LD mycheats.cpp /Fe:mycheats.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mycheats-dll
        path: mycheats.dll