name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Build DLL
        run: g++ -shared -o mycheats.dll mycheats.cpp -ld3d9

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: mycheats
          path: mycheats.dll